{% set name = "yaq-traits" %}
{% set version = "2021.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4743daf1b34cc13e270d4abb8d2e0c68ca7ac8001b22f7111040f0a7e87a53b0

build:
  number: 0
  noarch: python
  entry_points:
    - yaq-traits=yaq_traits.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - click
    - colorama
    - fastavro
    - prettytable
    - toml
    - flit
    - pip
    - python >=3.6
  run:
    - click
    - colorama
    - fastavro
    - prettytable
    - python >=3.6
    - toml

test:
  imports:
    - yaq_traits
  commands:
    - pip check
    - yaq-traits --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: package defining yaq traits
  dev_url: https://gitlab.com/yaq/yaq-traits
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
